### ISSUE TITLE
download yara

### ISSUE THREAD

**Issue by xyz2Q** [tromp/cuckoo#108]
hello，I want to set up this kind of downloadable yara rule for Cuckoo, can you help me，look forward to your answer, thank you。
![image](https://user-images.githubusercontent.com/54341480/124451888-70231380-ddb8-11eb-89b0-260a424c1413.png)

**Comment by tromp** [comment]
I doubt I can help, as I know know nothing about Yara...

**Comment by xyz2Q** [comment]
Okay, thank you
