### ISSUE TITLE
Read your aeternity.com postings about ASIC, but could not message you there.

### ISSUE THREAD

**Issue by IcannotThinkOfAnymoreNames** [tromp/cuckoo#110]
You seem to be the one to ask. I'm seeing single workers atop 2miners https://ae.2miners.com/miners "3.58 KGps" and woolypooly https://woolypooly.com/en/coin/ae "8.81 KGp/s" some exceed my own multi-worker/gpu rigs by over 100 times, with one worker hashing at 30+. Yet four years on from this important discussion, no ASIC exists, by my searching, for AE. Could these be farms spoofing as a single worker? Or is there an ASIC responsible for all of this hashpower?

**Comment by tromp** [comment]
The existing iPollo G1 (mini) ASIC miners can only solve Cuckatoo Cycle, and as far as I know, no ASICs have been made for Cuckoo Cycle. So I guess these are GPU farms reporting as a single miner.

**Comment by IcannotThinkOfAnymoreNames** [comment]
That is what my research found too, just thought I would check with an expert! Thanks.
