### ISSUE TITLE
Thanks a lot for your cpu miner.

### ISSUE THREAD

**Issue by lightningasic** [tromp/cuckoo#15]
we use gpu miner, don't use cpu to do mining. in order to thanks for your great works for zcash community. i send 0.5btc: https://blockchain.info/tx/f4b30f9975d42e5d30c7f6868ae120dfdf2aba67b55e60126d3410458a5321e0
ZCASH forum forbiddens me to send pm.
so, i have to send it here.
if possible, give me your email.

**Comment by tromp** [comment]
dear LightningASIC,

> we use gpu miner, don't use cpu to do mining.

It looks like cpus are more power efficient!
Only 2.5 Joule/Solution, where GPUs need over 5 Joule/Solution.
Anyway, I don't mine myself, but I think the GPUs have to try harder
to win the efficiency battle:-)

> in order to thanks for your great works for zcash community. i send 0.5btc: https://blockchain.info/tx/f4b30f9975d42e5d30c7f6868ae120dfdf2aba67b55e60126d3410458a5321e0

Thanks for your generous contribution to the Cuckoo Cycle Bounty Fund!

> ZCASH forum forbiddens me to send pm.
> so, i have to send it here.
> if possible, give me your email.

My email is clearly shown on my github:-)
It's john.tromp@gmail.com

regards,
-John

**Comment by marctmiller** [comment]
wtf is this terrible email, moron?

**Comment by auroracoin** [comment]
hi tromp  is there a way to mine zcash with my windows VISTA with my 750ti's  the cmd opens then closes on .2a any help plz  thx  sorry pm here  on thread bitcoin talk tbearhere
