### ISSUE TITLE
What is the baseline for the bounty??

### ISSUE THREAD

**Issue by billyfordon** [tromp/cuckoo#16]
I'm looking into this, but there is no clear baseline for the bounty. On the one hand, your Makefile defines bounty targets that use the regular miner (cuckoo_miner), but on the other hand, you have a SIMD implementation in bounty_miner (which I assume is much faster) that is not being used in the Makefile.

So what exactly are we supposed to beat here??

**Comment by tromp** [comment]
bounty_miner is just an outdated version of cuckoo_miner. I'll update it to avoid confusion...
