### ISSUE TITLE
[Question] Fair Mining License

### ISSUE THREAD

**Issue by sdtsui** [tromp/cuckoo#32]
@tromp , thanks for such a straightforward, well-documented repo!

Where can I find more info about the fair mining license and how it works? The description is [license.txt](https://github.com/tromp/cuckoo/blob/master/LICENSE.txt#L12) is a little brief. 

 If I'm interested in implementing a miner (or sponsoring an implementation)...
- How do I 'offer' half the revenue fee with developers?
- Who should I reach out to, and depending on the project, how will they accept coins?
- What happens if developers' addresses change, or get compromised?

Googled around a bit, wasn't able to find much on it. [This thread](https://forum.z.cash/t/about-dev-fees-and-how-to-remove-them/9600/83) on removing miner fees comes to mind.  **Happy to link to this issue/PR a documentation improvement if it is desired.**   Thank you.

**Comment by tromp** [comment]
Sorry for the delayed response; I was on vacation this past week...

I'm afraid there is no more info about the fair mining license. On a slack I wrote 

hi. the fair license is for coins with no developer compensation
it asks people like Claymore, who develop proprietary (closed source) miners with a small mining fee (eg 1%) to share half the fee with the coin developers so they can also get compensated for their efforts
if cuckoo cycle is used in a coin with an ICO or mining tax like Zcash, then the fair clause doesn't apply, and the likes of Claymore need not share any of their miner dev fees

> How do I 'offer' half the revenue fee with developers?

Contact them and ask how to arrange the sharing. This could be a once a month transfer to an address
or wallet they provide for this purpose.

> Who should I reach out to, and depending on the project, how will they accept coins?

You can reach out to the lead developer, who usually has a known github identity.

> What happens if developers' addresses change, or get compromised?

They should inform you of address change on a timely basis. If they get compromised
then that's their problem, not yours:-)
