### ISSUE TITLE
Modify value of M/N?

### ISSUE THREAD

**Issue by AnimatedRNG** [tromp/cuckoo#43]
Modifying the value of `NEDGES` causes most of the miners to crash -- is there an easy way to set the value of `M/N` (`M` edges and `N` vertices) to an arbitrary value (like 0.7)?

**Comment by tromp** [comment]
Only the simple miner supports M/N > 1/2. Edge trimming, as used by all other miners, requires M/N <= 1/2.
So you'd have to use the somewhat out-of-date Java miner...
