### ISSUE TITLE
Prerequisites - time and the LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by colibrae** [tromp/cuckoo#44]
I am working with an Arch Linux system, and I encountered two issues when building this code.

First was setting the LD_LIBRARY_PATH, for this, the command, which I found in another issue:

`export LD_LIBRARY_PATH=$PWD`

The second prerequisite was the 'time' command. On Arch Linux the function exists, I'm not 100% certain, but I think, within bash itself, and so the makefile was unable to run the timing tests until I installed the package with `pacman -S time`.

There is no build instructions in the README.md and I think these two things should be added in order to complete the documentation.

I found there is a note about in the Makefile...

**Comment by tromp** [comment]
Build instructions added and 'time's for common targets removed
