### ISSUE TITLE
mean30sx8 error

### ISSUE THREAD

**Issue by thepiwo** [tromp/cuckoo#51]
When running the build instructions on arch linux I get the following error:
```
./mean30sx8 -n 63
Looking for 42-cycle on cuckoo30("",63) with 50% edges
Using 3168MB bucket memory at 7f6bc0763010,
1x21MB thread memory at 7f6bbf272010,
8-way siphash, and 128 buckets.
nonce 63
genUnodes round  0 size 536870912 rdtsc: 5862158714
mean30sx8: mean_miner.hpp:198: u32 zbucket<BUCKETSIZE>::setsize(const u8*) [with unsigned int BUCKETSIZE = 202752; u32 = unsigned int; u8 = unsigned char]: Assertion `size <= BUCKETSIZE' failed.
```

The system is a i7 8700k with 32GB of DDR4
`Linux philipp-pc 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC 2018 x86_64 GNU/Linux`

avx and avx2 are supported as stated in the flags from `/proc/cpuinfo`

is there any more debugging information I can provide?

**Comment by tromp** [comment]
dear Philipp,

> When running the build instructions on arch linux I get the following error:
>
> ./mean30sx8 -n 63
> Looking for 42-cycle on cuckoo30("",63) with 50% edges
> Using 3168MB bucket memory at 7f6bc0763010,
> 1x21MB thread memory at 7f6bbf272010,
> 8-way siphash, and 128 buckets.
> nonce 63
> genUnodes round  0 size 536870912 rdtsc: 5862158714
> mean30sx8: mean_miner.hpp:198: u32 zbucket<BUCKETSIZE>::setsize(const u8*)
> [with unsigned int BUCKETSIZE = 202752; u32 = unsigned int; u8 = unsigned
> char]: Assertion `size <= BUCKETSIZE' failed.
>
> The system is a i7 8700k with 32GB of DDR4
> Linux philipp-pc 4.14.57-1-MANJARO #1 SMP PREEMPT Sun Jul 22 19:25:51 UTC
> 2018 x86_64 GNU/Linux
>
> avx and avx2 are supported as stated in the flags from /proc/cpuinfo
>
> is there any more debugging information I can provide?

Hmm, I cannot reproduce that on my system. Can you check whether this
also happens
with mean30x8 and mean30x1?
Is there a way for me to debug this on your machine?

regards,
-John

**Comment by thepiwo** [comment]
Thank you, I did email you about the possibility to debug on my machine.

**Comment by tromp** [comment]
determined to be compiler issue (generation of incorrect SSE2 code)
