### ISSUE TITLE
Whitepaper has a missing reference

### ISSUE THREAD

**Issue by lvella** [tromp/cuckoo#61]
I am not sure this is the proper place to report it, but whitepaper has a missing reference ([?]) at the second paragraph in page 2.

**Comment by tromp** [comment]
That's

@article{parallel99}
 author = {van Oorschot, Paul C. and Wiener, Michael J.},
 title = {Parallel collision search with cryptanalytic applications},
 journal = {J. Cryptology},
 12(1):1–28, 1999.
 issue_date = {Jan 1999},
 volume = {12},
 number = {1},
 month = jan,
 year = {1999},
 pages = {1--28},
 numpages = {28},
} 

will be fixed when I finish work on dev branch...
