### ISSUE TITLE
Feature request: Add structured output

### ISSUE THREAD

**Issue by casey** [tromp/cuckoo#64]
I'm working on a tool that runs a bunch of cuckoo cycle solvers and saves output (including time, 
algorithm use, and graph size) to a file. The hope is that people in the community will use this tool to benchmark and report their GPU/CPU performance, which I can then use to produce a public website that shows the performance of the different solvers and algorithms across different GPUs and CPUs.

You can see the current work in progress code [here](https://github.com/casey/cuckoo-bench).

Parsing data from the solver output was pretty painful. Would you consider adding some kind of structured output, for example JSON, to make such tools easier to write? Ideally it would log all parameters that the solver was launched with, information on the CPU or GPU which the solver was running on, and information about solution times for the graphs searched.

**Comment by casey** [comment]
😭Yes, yes I would.

**Comment by casey** [comment]
What is the suggested way to call that function? It's defined in `mean.cu`, along with `main`, but I'd like to call it from a separate binary with a different main function.

**Comment by tromp** [comment]
> What is the suggested way to call that function? It's defined in mean.cu, along with main, but I'd like to call it from a separate binary with a different main function.

If you compile mean.cu into a .so library, the main() function will be
ignored and absent in the library.
You can then write your own program using the API and link with the
library. That's what grin-miner does.

regards,
-John

**Comment by casey** [comment]
Gotcha, that makes sense. Thanks!
