### ISSUE TITLE
not work on NVIDIA GeForce GTX 750 Ti

### ISSUE THREAD

**Issue by nevata** [tromp/cuckoo#75]
-d 0 -E 0 -h "" -m 176 -n 0 -r 1 -U 4096 -u 256 -v 128 -w 512 -y 1024 -Z
 1024 -z 1024

The thread 0x1c84 has exited with code 0 (0x0).
The thread 0x1160 has exited with code 0 (0x0).
The thread 0x2a30 has exited with code 0 (0x0).
First-chance exception at 0x01049349 in vs2013.exe: 0xC0000005: Access violation reading location 0x08812770.
Unhandled exception at 0x01049349 in vs2013.exe: 0xC0000005: Access violation reading location 0x08812770.

class cuckoo_hash {
public:
  u64 *cuckoo;

  cuckoo_hash() {
    cuckoo = new u64[CUCKOO_SIZE];
  }
  ~cuckoo_hash() {
    delete[] cuckoo;
  }
  void set(node_t u, node_t v) {
    u64 niew = (u64)u << NODEBITS | v;
    for (node_t ui = u >> IDXSHIFT; ; ui = (ui+1) & CUCKOO_MASK) {
      u64 old = cuckoo[ui]; //error at
      if (old == 0 || (old >> NODEBITS) == (u & KEYMASK)) {
        cuckoo[ui] = niew;
        return;
      }
    }
  }
  node_t operator[](node_t u) const {
    for (node_t ui = u >> IDXSHIFT; ; ui = (ui+1) & CUCKOO_MASK) {
      u64 cu = cuckoo[ui]; //error at
      if (!cu)
        return 0;
      if ((cu >> NODEBITS) == (u & KEYMASK)) {
        assert(((ui - (u >> IDXSHIFT)) & CUCKOO_MASK) < MAXDRIFT);
        return (node_t)(cu & NODEMASK);
      }
    }
  }
};

**Comment by nevata** [comment]
Thank you, I use GTX 1080 has error:

C:\DevRoot\cuckoo\vs2013\x64\Debug>vs2013.exe -d 0 -E 0 -h "" -m 176 -n 0 -r 1 -U 4096 -u 256 -v 128 -w 512 -y 1024 -Z 1024 -z 1024
GeForce GTX 1080 with 8192MB @ 256 bits x 5005MHz
Looking for 42-cycle on cuckoo30("",0) with 50% edges, 64*64 buckets, 176 trims, and 64 thread blocks.
MALLOC: -1275068416
Using 6976MB of global memory.
Error initialising trimmer. Aborting.
Reason: Device 0 GPUassert: out of memory C:/DevRoot/cuckoo/src/cuckoo/mean.cu 389

**Comment by tromp** [comment]
The 1080 has more than 7 GB of memory, so it shouldn't be out.
I don't know where that MALLOC: -1275068416 comes from.
Apparently the solver doesn't build correctly under Windows.
But I have no experience with or way to diagnose Windows problems.

**Comment by timolson** [comment]
Just a guess... Looks like overflow of a signed 32-bit integer.  Make sure
you’re building on a 64-bit platform. 32-bit addressing can only go up to
4GB.
