### ISSUE TITLE
Reduce cudaMemcpy size of hostA to sizeof(u32)

### ISSUE THREAD

**Issue by bigtreeliujie** [tromp/cuckoo#76]
cuckoo/mean.cu
cuckaroo/mean.cu
cuckatoo/mean.cu

```
cudaMemcpy(hostA, indexesE, NX * NY * sizeof(u32), cudaMemcpyDeviceToHost);
```
should be change to 
```
cudaMemcpy(hostA, indexesE, sizeof(u32), cudaMemcpyDeviceToHost);
```
to reduce io between device and host a little?

**Comment by tromp** [comment]
Well spotted! This line dates back from before we added the Tail kernel for edge compaction.
Will fix in next update... Thanks!
