### ISSUE TITLE
cuckaroo/cuda29 doesn't seem to work with Nvidia RTX 2070 GPUs

### ISSUE THREAD

**Issue by mably** [tromp/cuckoo#77]
Here are the logs we get when running the cuda29 utility program with `-r 100` parameter:

https://pastebin.com/raw/xErhKHcE

**Comment by tromp** [comment]
are you sure you built from the latest commit?
your output me of the bug i fixed in https://github.com/tromp/cuckoo/commit/609dde26dbfa2a1637b64a288498422955b20162

**Comment by tromp** [comment]
If you can provide remote access to your machine, I can try to debug it there.

**Comment by couillardcharles** [comment]
@tromp I can give you a remote access to the machine. (machine with a 2080, a 2070, a 1080 ti and a 1070 ti)

**Comment by couillardcharles** [comment]
@tromp sent info via keybase

**Comment by mably** [comment]
Looks like our RTX 2070 card might be faulty.

It would be great if anyone could confirm that cuckaroo29 works fine on their 2070 gpu.
