### ISSUE TITLE
What's the meaning of pathcount[] in `cyclebase.hpp`?

### ISSUE THREAD

**Issue by xiongyw** [tromp/cuckoo#90]
I did not figure out the meaning and usage of it yet...

Many thanks!

**Comment by tromp** [comment]
Currently, it's only used to determine if a node has an outgoing edge.
That is, pathcount[u] !=  0 if and only if cuckoo[u] has been set to point to another node.
It was introduced to try find more cycles than just a cycle base, but I later realized this was a dead-end
approach and instead I ended up implementing the DFS based search in cucka[rt]oo/graph.hpp
With the current limited use of pathcount, the above condition is equivalent to cuckoo[u] != -1, so it could easily be eliminated.

**Comment by xiongyw** [comment]
Got it, thanks a lot.
