### ISSUE TITLE
Are cuckroo and cucktoo using the same find cycles' algorithm?

### ISSUE THREAD

**Issue by FivePeter** [tromp/cuckoo#94]
Using DFS, cucktoo needs to store a lot of information.
Thanks

**Comment by tromp** [comment]
yes, cuckoo/src/cucka{r,t}oo/graph.hpp implements the dfs cycle finder
Slides 24 and 25 show the space requirements of the cyclebase finder and dfs cycle finer respectively.
you can reduce these by doing more trimming beforehand...

**Comment by FivePeter** [comment]
Can I use the directed cuckoo graph to find cucktoo's  cycles？For example， the following figure has two paths, D1->A2, A1->C1。When adding (A1,C2),I don't know its direction, A1->C2 or C2->A1?

A1  A2        B1   B2

C1   C2       D1  D2

Thanks

**Comment by tromp** [comment]
I don't see how. But note that the cyclebase finder maintains a directed forest, where all edges in a single component tree are directed to its root.
